// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9BmoScO5wiVsVmg6DktnNh-USi33oBI8',
    appId: '1:322544754519:web:4f8af72744d58b0b912812',
    messagingSenderId: '322544754519',
    projectId: 'uas-catatan',
    authDomain: 'uas-catatan.firebaseapp.com',
    storageBucket: 'uas-catatan.appspot.com',
    measurementId: 'G-S376WY36XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR37ExjwQ8CtjoWqay2l1Gj0u6hSVDx4s',
    appId: '1:322544754519:android:5edaa78f42dd68fe912812',
    messagingSenderId: '322544754519',
    projectId: 'uas-catatan',
    storageBucket: 'uas-catatan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7k6C3vTl5OieqOMcMRVeuzGky65s77hQ',
    appId: '1:322544754519:ios:79e466efc24251ce912812',
    messagingSenderId: '322544754519',
    projectId: 'uas-catatan',
    storageBucket: 'uas-catatan.appspot.com',
    iosClientId: '322544754519-35q7ik2ntqhr5ulq7ld3vjcprj0g7k42.apps.googleusercontent.com',
    iosBundleId: 'com.example.catatanUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7k6C3vTl5OieqOMcMRVeuzGky65s77hQ',
    appId: '1:322544754519:ios:79e466efc24251ce912812',
    messagingSenderId: '322544754519',
    projectId: 'uas-catatan',
    storageBucket: 'uas-catatan.appspot.com',
    iosClientId: '322544754519-35q7ik2ntqhr5ulq7ld3vjcprj0g7k42.apps.googleusercontent.com',
    iosBundleId: 'com.example.catatanUas',
  );
}
